---
title: "Signature extraction from Canadas et al 2018"
output: html_notebook
---

# Import data

```{r}
# Version info: R 3.2.3, Biobase 2.30.0, GEOquery 2.40.0, limma 3.26.8
# R scripts generated  Fri Aug 31 00:53:50 EDT 2018


# Server: www.ncbi.nlm.nih.gov
# Query: acc=GSE45120&platform=GPL6244&type=txt&groups=ZR-75-1|ZR-75-30&colors=dfeaf4|f4dfdf&selection=XXXXXX&padj=fdr&logtransform=auto&columns=ID&columns=adj.P.Val&columns=P.Value&columns=t&columns=B&columns=logFC&columns=Gene+symbol&columns=Gene+title&num=250&annot=ncbi

# Unable to generate script analyzing differential expression.
#      Invalid input: at least two groups of samples should be selected.

################################################################
#   Boxplot for selected GEO samples
library(Biobase)
library(GEOquery)

# load series and platform data from GEO

canadas_data <- paste(getwd(),"../..","datasets","canadas_2018/",sep = "/")
gset_canadas0 <- getGEO("GSE45120", GSEMatrix =TRUE, getGPL=FALSE,destdir = canadas_data)
if (length(gset_canadas0) > 1) idx <- grep("GPL6244", attr(gset, "names")) else idx <- 1
gset_canadas <- gset_canadas0[[idx]]

# # set parameters and draw the plot
# palette(c("#dfeaf4","#f4dfdf", "#AABBCC"))
# dev.new(width=4+dim(gset)[[2]]/5, height=6)
# par(mar=c(2+round(max(nchar(sampleNames(gset)))/2),4,2,1))
# title <- paste ("GSE45120", '/', annotation(gset), " selected samples", sep ='')
# boxplot(exprs(gset), boxwex=0.7, notch=T, main=title, outline=FALSE, las=2)

```

## log2 transform
```{r}
# log2 transform
exfull <- exprs(gset_canadas)
gset_canadas_trsf <- gset_canadas
qxfull <- as.numeric(quantile(exfull, c(0., 0.25, 0.5, 0.75, 0.99, 1.0), na.rm=T))
LogCfill <- (qxfull[5] > 100) ||
          (qxfull[6]-qxfull[1] > 50 && qxfull[2] > 0) ||
          (qxfull[2] > 0 && qxfull[2] < 1 && qxfull[4] > 1 && qxfull[4] < 2)
if (LogC) { exfull[which(exfull <= 0)] <- NaN
  exprs(gset_canadas_trsf) <- log2(exfull) }

```

# Differential expression analysis 

The data came from a one-channel microarray

```{r print_description}
print(gset_canadas$description)
```

## Set design 
This is a pretty simple experimental setup: two conditions, one H69M and one H69 (both cell lines). We should consider how lung-cancer inflammation responses vary from EOC, Breast, or Colon cancer responses (as in Li et al 2014 and Chiappinelli et al 2015)

```{r set_design}
gset_canadas_meta <- data.frame(celltype=gset_canadas$`cell line:ch1`)

```

## Model fit

```{r model_fit}

by_cell_fits <- lapply(unique(by_celltype_time$cellgroup),
                      function(x) {
                        x.meta <- subset(by_celltype_time,cellgroup %in% x)
                        x.gset <- gset_trsf[,x.meta$sample]
                        x.design <- model.matrix(~ 0 + time, 
                                     x.meta)
                        # remove the zero-columns
                        x.design <- x.design[,colSums(x.design) > 0]
                        x.fit <- lmFit(x.gset, x.design)
                        x.fit
                      })
names(by_cell_fits) <- unique(by_celltype_time$cellgroup)


```

