#!/bin/bash
#SBATCH -p medium
#SBATCH -t 0-48:00
#SBATCH -n 4
#SBATCH -N 1
#SBATCH --mem=12G
#SBATCH -o %j.out.txt #outfile
#SBATCH -e %j.err.txt #errfile

module load gcc/6.2.0 sratoolkit/2.8.1

inlist=$1
outdir=$2

# isolate the entry in the incoming list
taskid=$SLURM_ARRAY_TASK_ID
insrr=$(sed -n $taskid'p' $inlist)
echo -e "SRA accession: $insrr"
# jobname=$(basename $infile)
# jobname=${jobname%$filesuffix}

# get the srrnumber
# srrnum=${insrr#*SRR}
srrnum=${insrr:0:6}
echo -e "SRA accession #: $srrnum"

wget --directory-prefix=$outdir ftp://ftp-trace.ncbi.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/$srrnum/$insrr/$insrr.sra
fastq-dump --split-files --outdir $outdir --gzip $outdir/$insrr.sra

# rename statements
# mv $insrr"_1.fastq.gz" $insirr"_R1.fastq.gz"
# mv $insrr"_2.fastq.gz" $insirr"_R2.fastq.gz"

echo -e "fastq-dump --outdir $outdir --gzip $insrr" >> $outdir/jobsubmit.txt
